### ISSUE TITLE
Would it make sense to add a IsList instance?

### ISSUE THREAD

**Issue by dnadales** [joelwilliamson/bimap#13]
Is there a reason why there's no `IsList` instance? If such instance would make sense I could submit a PR for adding it :pray:

**Comment by joelwilliamson** [comment]
This was already done by intricate a few months ago.
https://github.com/joelwilliamson/bimap/pull/10

**Comment by dnadales** [comment]
Oh, I see. I was using an old version then. Sorry for the confusion :pray:
