### ISSUE TITLE
Test Hackage v0.5.0

### ISSUE THREAD

**Issue by joelwilliamson** [joelwilliamson/bimap#17]
@ivanperez-keera @intricate @bingis-khan 

I just uploaded v0.5 containing both the recent changes to Hackage. Would one of you mind testing to make sure it's usable?

**Comment by andreasabel** [comment]
You could use https://github.com/haskell-CI/haskell-ci to set up a CI on github actions quite automatically.  
Example:
- Demo config (can also be empty initially): https://github.com/haskell-hvr/regex-tdfa/blob/40144da17a6c845d2a130eeaab6686cbce0fada5/cabal.haskell-ci
- Generated workflow: https://github.com/haskell-hvr/regex-tdfa/blob/40144da17a6c845d2a130eeaab6686cbce0fada5/.github/workflows/haskell-ci.yml

**Comment by ivanperez-keera** [comment]
@joelwilliamson I have confirmed that the current version 0.5.0 would work well with `copilot`. All installs correctly, the module that uses `bimap` is marked as Safe, and the `copilot` examples also run correctly.
