### ISSUE TITLE
Why require Ord on map and mapR?

### ISSUE THREAD

**Issue by karljs** [joelwilliamson/bimap#5]
Sorry if I'm missing something obvious, but why do you have the `Ord` constraint on `map` and `mapR`?

**Comment by joelwilliamson** [comment]
Data.Map.mapKeys has an Ord constraint.

**Comment by joelwilliamson** [comment]
To expand, a Bimap is a pair of maps, one from `a` to `b`, and the other from `b` to `a`. Whenever a key or value type is changed, it must have an Ord constraint for the map keyed on that type to work.

**Comment by karljs** [comment]
Thanks, I understand.  I was thinking, stupidly, that you wouldn't need to map across the keys for some reason since you store both maps.
